WITH PairProfitability AS (
    SELECT 
        sd1.itemno AS item_a_id,
        si1.name AS item_a_name,
        sd1.qty AS item_a_qty,
        sd2.itemno AS item_b_id,
        si2.name AS item_b_name,
        sd2.qty AS item_b_qty,
        COUNT(DISTINCT sd1.reference_number) AS pairs_order_count,
        -- Calculate the combined profit generated by both items across all orders where they co-occur
        SUM(
            (((sd1.qty * sd1.ice) - (sd1.qty * sd1.cost)) * CASE WHEN sd1.fcy = '01' THEN 0.002421307506053 WHEN sd1.fcy = '02' THEN 3.8 ELSE 1 END) +
            (((sd2.qty * sd2.ice) - (sd2.qty * sd2.cost)) * CASE WHEN sd2.fcy = '01' THEN 0.002421307506053 WHEN sd2.fcy = '02' THEN 3.8 ELSE 1 END)
        ) AS combined_pair_profit
    FROM silver.sales_order_detail sd1
    INNER JOIN silver.sales_order_detail sd2 
        ON sd1.reference_number = sd2.reference_number
        AND sd1.itemno < sd2.itemno
    INNER JOIN silver.stock_item si1 
        ON sd1.itemno = si1.itemno
    INNER JOIN silver.stock_item si2 
        ON sd2.itemno = si2.itemno
    WHERE sd1.invdate > '20211231'
        AND TRIM(sd1.itemno) != '1'
        AND TRIM(sd2.itemno) != '1'
    GROUP BY 
        sd1.itemno, si1.name, sd1.qty,
        sd2.itemno, si2.name, sd2.qty
),
ItemBaseCounts AS (
    SELECT 
        itemno,
        COUNT(DISTINCT reference_number) AS total_item_orders
    FROM silver.sales_order_detail
    WHERE invdate > '20211231'
    GROUP BY itemno
)
SELECT 
    pp.item_a_name AS "ITEM A",
    pp.item_a_qty AS "QTY A",
    pp.item_b_name AS "ITEM B",
    pp.item_b_qty AS "QTY B",
    TO_CHAR(pp.pairs_order_count, 'FM9,999,999') AS "ORDERS TOGETHER",
    TO_CHAR((pp.pairs_order_count::float / ibc.total_item_orders) * 100, 'FM990.00') || '%' AS "CONFIDENCE (A -> B)",
    TO_CHAR(pp.combined_pair_profit, 'FM9,999,999.00') AS "COMBINED NET PROFIT"
FROM PairProfitability pp
INNER JOIN ItemBaseCounts ibc 
    ON pp.item_a_id = ibc.itemno
WHERE pp.pairs_order_count > 5
-- Sort dynamically by combined profit, then by transaction frequency
ORDER BY pp.combined_pair_profit DESC, pp.pairs_order_count DESC
LIMIT 50;