-- Load: bronze.sales_hd -> silver.sales_order_header
TRUNCATE TABLE silver.sales_order_header CASCADE;

-- DISTINCT ON ("company", "invtype", "ref")
-- DISTINCT ON ("company", "invtype", "ref", "folio") 

INSERT INTO silver.sales_order_header ("slcenter", "anch", "company_id", "invoice_type", "reference_number", "invoice_date", "custno", "custnm", "glser", "dsctype", "pstmode", "fcy", "fcyrate", "duedate", "invttl", "invcst", "invdspc", "invdsvl", "valafds", "invpaid", "caser", "entries", "released", "posted", "fixrate", "extamt", "extser", "icetp", "ischeque", "chkno", "chkdate", "lastupdt", "jvgenrt", "cccommsn", "belowbal", "fcy2", "ccpayment", "rplsamt", "pdother", "slcode", "paidamt", "instldays", "instflag", "slcmnd", "inv_printed", "bendit", "modified", "rqstorder", "rqststld", "carrier", "rcvdtrn", "usrid", "address", "suspend", "rtnref", "ispurchase", "stkjvno", "posinv", "sanedcrd_amt", "remarks", "remarks2", "invlocked", "rtncash_dfrpl", "vat_amt_rcvd", "taxfree_sales", "clnt_taxcode", "clnt_kind", "hlldscnt", "sysno", "no_round_nm", "icevattype", "smssent", "stcpay_amt", "fc2lcamt", "qitaf_amt", "whlslinv", "vat_percent", "fsh_printed", "fqtyval", "fc_whrate", "is_numerator", "datetime_stamp", "fusrprintinv", "almnm_contract_section", "mobileno", "client_name", "installment_amt", "zatca_rounding", "tac_fees_percent", "tac_fees_amount", "tac_fees_account", "discountedbill", "icetacfeestype")
SELECT  "slcenter", "branch", "company", "invtype", "ref", "invdate", "custno", "custnm", "glser", "dsctype", "pstmode", "fcy", "fcyrate", "duedate", "invttl", "invcst", "invdspc", "invdsvl", "valafds", "invpaid", "caser", "entries", "released", "posted", "fixrate", "extamt", "extser", "pricetp", "ischeque", "chkno", "chkdate", "lastupdt", "jvgenrt", "cccommsn", "belowbal", "fcy2", "ccpayment", "rplsamt", "pdother", "slcode", "prpaidamt", "instldays", "instflag", "slcmnd", "inv_printed", "bendit", "modified", "rqstorder", "rqststld", "carrier", "rcvdtrn", "usrid", "address", "suspend", "rtnref", "ispurchase", "stkjvno", "posinv", "sanedcrd_amt", "remarks", "remarks2", "invlocked", "rtncash_dfrpl", "vat_amt_rcvd", "taxfree_sales", "clnt_taxcode", "clnt_kind", "hlldscnt", "sysno", "no_round_nm", "pricevattype", "smssent", "stcpay_amt", "fc2lcamt", "qitaf_amt", "whlslinv", "vat_percent", "fsh_printed", "fqtyval", "fc_whrate", "is_numerator", "datetime_stamp", "fusrprintinv", "almnm_contract_section", "mobileno", "client_name", "installment_amt", "zatca_rounding", "tac_fees_percent", "tac_fees_amount", "tac_fees_account", "discountedbill", "pricetacfeestype"
FROM bronze.sales_hd 
ORDER BY "company", "invtype", "ref", _source_archive DESC;

-- Load: bronze.sales_dt -> silver.sales_order_detail
TRUNCATE TABLE silver.sales_order_detail CASCADE;

INSERT INTO silver.sales_order_detail ("sales_center", "company_id", "invoice_type", "reference_number", "invoice_date", "item_number", "item_quantity", "free_quantity", "unit_price", "discpc", "unit_cost", "ds_acfm", "acfm", "gclass", "customer_number", "foreign_currency", "barcode", "imfcval", "pack", "pkqty", "shadd", "shdpk", "shdqty", "frtqty", "rtnqty", "warehouse_number", "cmbkey", "folio", "rplct_post", "sold_item_status", "taxtype", "ps_item_vat", "dsc_amt", "expdate", "item_price_net", "invdscamt", "item_vat")
SELECT "slcenter", "company", "invtype", "ref", "invdate", "itemno", "qty", "fqty", "price", "discpc", "cost", "ds_acfm", "sl_acfm", "gclass", "custno", "fcy", "barcode", "imfcval", "pack", "pkqty", "shadd", "shdpk", "shdqty", "frtqty", "rtnqty", "whno", "cmbkey", "folio", "rplct_post", "sold_item_status", "taxtype", "ps_item_vat", "dsc_amt", "expdate", "item_price_net", "invdscamt", "item_vat"
FROM bronze.sales_dt 
ORDER BY "company", "invtype", "ref", "folio", _source_archive DESC;